name: 'Test DCP Deploy'

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ] # , 'windows-latest', 'macos-latest' ]
        python_version: [ '3.10' ]
        node_version: [ 16 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - run: python3 -m pip install -r ./dev-requirements.txt
      - run: python3 ./setup.py install
      - name: run tests
        shell: 'script -q -e -c "bash {0}"'
        env:
          DCP_ACCOUNT_KEYSTORE: ${{ secrets.ACCOUNT_KEYSTORE }}
          DCP_ID_KEYSTORE: ${{ secrets.ID_KEYSTORE }}
          DCP_ARTIFACTS_TOKEN: ${{ secrets.ARTIFACTS_ACCESS_TOKENS }}
        run: |
          mkdir -p ~/.dcp
          echo $DCP_ACCOUNT_KEYSTORE > ~/.dcp/default.keystore
          echo $DCP_ID_KEYSTORE > ~/.dcp/id.keystore
          chmod og-w ~/.dcp -R
          echo "Prep Native Worker"
          sudo npm i dcp-worker -g &> /dev/null 
          echo curl --output ./artifacts.zip --location --header "PRIVATE-TOKEN: ${DCP_ARTIFACTS_TOKEN}" "https://gitlab.com/api/v4/projects/25835277/jobs/3293593922/artifacts"
          #unzip ./artifacts.zip && unzip ./dcp-native-1.2.0-Linux.zip
          #rm -rf ./artifacts.zip ./dcp-native-1.2.0-Linux.zip
          #echo "Native worker downloaded"
          #echo "Starting evaluator"
          echo "PRIVATE TOKEN HAS SIZE: " ${#DCP_ARTIFACTS_TOKEN}
          ls -lah ./
          #dcp-evaluator-start -e /artifacts/binary/Release/dcp-evaluator -l /artifacts/binary/Release/ -p 9000 &
          #sleep 10
          #kill %1

          #echo "READY TO RUN TESTS"
          #./run-tests.sh
      - name: clean up
        if: always()
        run: |
          rm -rf ~/.dcp
