name: 'Test DCP Deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '*'
  pull_request:

jobs:
  run_tests:
    name: "run-tests"
    runs-on: ubuntu-latest
    test_matrix:
      strategy:
        matrix:
          python_version: [ '3.10' ]
          node_version: [ 16 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - run: python3 -m pip install -r ./dev-requirements.txt
