name: 'Test DCP Deploy'

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python_version: [ '3.10' ]
        node_version: [ 16 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - run: python3 -m pip install -r ./dev-requirements.txt
      - run: python3 ./setup.py install
